name: CraftingEngine
main: com.vanwaarda.CraftingEngine.CraftingEngine
version: 1.2.0
description: Vanwa-arda custom crafting.
load: POSTWORLD
author: ShadowSplicer
website: https://vanwa-arda.com/

commands:
  crafting:
    description: Shows what custom crafting items there are
    usage: /crafting
    permission: crafting.info
    permission-message: You don't have permission to do that.
permissions:
  crafting.info:
    description: Shows what custom crafting items there are
    default: true